from .landing import *
from .signup import *
from .login import *
from .logout import *
from .map import *
from .warehouse import *
from .store import *
from .friend import *
from .feed import *
from .home import *
from .racing import *
from .gameroom import *
from .flappy import *
from .hitmouse import *
from .playcastle import *
from .lovewall2 import *
